resource_types:
  - name: rss-resource
    type: docker-image
    source:
      repository: starkandwayne/concourse-rss-resource
      tag: develop

resources:
  - name: test-rss-resource
    type: rss-resource
    source:
      url: https://starkandwayne.com/blog/rss/

jobs:
  - name: test-rss-resource
    plan:
    - get: test-rss-resource
      trigger: true

    - task: alert
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: echo
          args: ["I cant believe this works"]
