resource_types:
  - name: rss
    type: docker-image
    source:
      repository: starkandwayne/rss-resource
      tag: latest

resources:
  - name: feed
    type: rss
    source:
      url: https://starkandwayne.com/blog/rss/

jobs:
  - name: test-rss-resource
    plan:
    - get: feed
      trigger: true

    - task: alert
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: ubuntu}
        run:
          path: echo
          args: ["I cant believe this works"]
